### PR TITLE
hotspot + name convention update 

### PR DESCRIPTION
**Pull request by DannyS03**
https://github.com/OpenLiberty/guides-common/issues/352
https://github.com/OpenLiberty/guides-common/issues/308

https://github.com/OpenLiberty/guide-jpa-intro/pull/117

### CODE REVIEW

**Comment by gkwan-ibm** [comment]
@DannyS03 
- [ ] would you update 2019 to 2020 for the updated java files?

**Comment by NimG98** [comment]
### Defining a JPA entity class

- [ ] Add file hotspot (or class hotspot) for `Event` class
    > The Event class is a data model that represents events in the event microservice and is annotated with JPA annotations.

### Configuring JPA

- [ ] Add file hotspot for `persistence.xml`
    > The persistence.xml file is a configuration file that defines a persistence unit. 
- [ ] `server.xml` need blank line before the end of the `</server>` tag

### Performing CRUD operations using JPA
- [ ] Add file hotspot (or class hotspot) for `EventDao`
    > To perform these operations by using JPA, we need an EventDao class.
- [ ] annotations in `EventResource.java` should have space above them, not below them:
    image

**Comment by gkwan-ibm** [comment]
@DannyS03 Please create a new PR to address Nimrah's feedback.

**Comment by DannyS03** [comment]
> ### Defining a JPA entity class
> 
>     * [x]  Add file hotspot (or class hotspot) for `Event` class
>       > The Event class is a data model that represents events in the event microservice and is annotated with JPA annotations.
> 
> 
> ### Configuring JPA
> 
>     * [x]  Add file hotspot for `persistence.xml`
>       > The persistence.xml file is a configuration file that defines a persistence unit.
> 
>     * [x]  `server.xml` need blank line before the end of the `</server>` tag
> 
> 
> ### Performing CRUD operations using JPA
> 
>     * [x]  Add file hotspot (or class hotspot) for `EventDao`
>       > To perform these operations by using JPA, we need an EventDao class.
> 
>     * [x]  annotations in `EventResource.java` should have space above them, not below them:
>       image

https://github.com/OpenLiberty/guide-jpa-intro/pull/123

**Pull request merged**
